tunnel: agnos-tunnel
credentials-file: /Users/alexander-highground/.cloudflared/fa140e1c-2573-48b9-a32f-1d9922fc83aa.json

ingress:
  - hostname: drive.fernhw.com
    service: http://127.0.0.1:80
  - hostname: office.fernhw.com
    service: http://127.0.0.1:7991
  - hostname: vault.fernhw.com
    service: http://127.0.0.1:7992
  - hostname: request.fernhw.com
    service: http://127.0.0.1:8770
  - service: http_status:404